---
- task:
    name: Start up task
    cmd: echo 'Starting up!'

- env:
    - foo: bar
    - baz: '`cat baz.json | jq -r .baz`'
    - greeting: eric
    - hello: $greeting

- envscript: 'curl http://httpbin.org/ip'

- template:
    template: examples/my.conf.tmpl
    target: examples/my.conf
    owner: nobody
    group: nobody
    mode: 0600

- post:
    - task:
        name: Finish task
        cmd: 'echo "All Done!"'
