---
- service:
    name: web-server
    cmd: go run server.go

- env:
    foo: bar
    baz: '`cat baz.json | jq -r .baz`'

- envscript: 'curl http://httpbin.org/ip'

- task:
    name: apt
    cmd: 'echo "apt get updating..."'
    dir: '/tmp'
