---

- env:
    PATH: $PATH

- task:
    name: build web server
    cmd: 'go build -o examples/web-server examples/server.go'

- service:
    name: web-server
    cmd: ./web-server

- env:
    foo: bar
    baz: '`cat baz.json | jq -r .baz`'

- envscript: 'curl http://httpbin.org/ip'

- task:
    name: apt
    cmd: 'echo "apt get updating..."'
    dir: '/tmp'

- post:
    - task:
        name: saying done
        cmd: 'echo "finished"'
