---
- env:
    PATH: $PATH

- task:
    name: build web server
    cmd: 'go build -o web-server server.go'

- service:
    name: sleeper
    cmd: sleep 60

- env:
    foo: bar
    baz: '`cat baz.json | jq -r .baz`'

- envscript: 'curl http://httpbin.org/ip'

- template:
    template: examples/my.conf.tmpl
    target: examples/my.conf
    owner: nobody
    group: nobody
    mode: 0600

- task:
    name: apt
    cmd: 'echo "apt get updating..."'
    dir: '/tmp'

- post:
    - task:
        name: saying done
        cmd: 'echo "finished"'
